-- Generated by mame_mcp. Installs read/write taps and dumps a deduped table.
local CONFIG = {
  frames = 20000,
  log_path = "C:/Users/meath/OneDrive/Documents/Sega System 24/.mame_mcp/gground_trace_20260807_001341.log",
  inject_preset = "none",
  ranges = {
    { name = "mixer", start = 0x404000, stop = 0x40401F },
  },
  track_reads = {

  },
}

local log = assert(io.open(CONFIG.log_path, "w"))
local function w(s) log:write(s .. "\n"); log:flush() end

local seen = {}
local order = {}
local tracked = {}
local frame = 0
local cpu = manager.machine.devices[":maincpu"]
local prog = cpu.spaces["program"]
MAME_MCP_TAPS = {}

local function pc()
  local ok, v = pcall(function() return cpu.state["PC"].value end)
  return ok and v or 0
end

local function record(rw, range_name, addr, data)
  local curpc = pc()
  local key = string.format("%s:%06X:%06X:%s", rw, curpc, addr, range_name)
  if not seen[key] then
    seen[key] = { count = 0, last = data, pc = curpc, addr = addr, rw = rw, range = range_name }
    order[#order + 1] = key
  end
  seen[key].count = seen[key].count + 1
  seen[key].last = data

  if rw == "R" then
    for _, t in ipairs(CONFIG.track_reads) do
      if addr == t.address then
        local bucket = tracked[t.name] or { address = t.address, values = {} }
        bucket.values[data] = (bucket.values[data] or 0) + 1
        tracked[t.name] = bucket
      end
    end
  end
end

for _, r in ipairs(CONFIG.ranges) do
  local range_name = r.name
  MAME_MCP_TAPS[#MAME_MCP_TAPS + 1] = prog:install_read_tap(r.start, r.stop, "mame_mcp_" .. range_name .. "_r",
    function(offset, data, mask) record("R", range_name, offset, data & 0xff); return data end)
  MAME_MCP_TAPS[#MAME_MCP_TAPS + 1] = prog:install_write_tap(r.start, r.stop, "mame_mcp_" .. range_name .. "_w",
    function(offset, data, mask) record("W", range_name, offset, data & 0xff); return data end)
end

local function find_field(namesub)
  for _, port in pairs(manager.machine.ioport.ports) do
    for fname, field in pairs(port.fields) do
      if fname:find(namesub, 1, true) then return field end
    end
  end
end

local function setfield(field, v) if field then field:set_value(v) end end
local coin, start
local schedule = {
  [240] = function() w("# inject: COIN1 down"); setfield(coin, 1) end,
  [260] = function() setfield(coin, 0); w("# inject: COIN1 up") end,
  [320] = function() w("# inject: COIN1 down 2"); setfield(coin, 1) end,
  [340] = function() setfield(coin, 0) end,
  [460] = function() w("# inject: START1 down"); setfield(start, 1) end,
  [490] = function() setfield(start, 0); w("# inject: START1 up") end,
}

local function dump_and_exit()
  for _, key in ipairs(order) do
    local e = seen[key]
    w(string.format("%s   %06X   %06X   %-16s %5d   $%02X", e.rw, e.pc, e.addr, e.range, e.count, e.last))
  end

  w("")
  w("# MAME_MCP_SUMMARY_BEGIN")
  w(string.format("# unique_accesses %d", #order))
  for _, t in ipairs(CONFIG.track_reads) do
    local bucket = tracked[t.name]
    w(string.format("# track %s $%06X", t.name, t.address))
    if bucket then
      for value, count in pairs(bucket.values) do
        w(string.format("#   $%02X read %d times", value, count))
      end
    end
  end
  w("# MAME_MCP_SUMMARY_END")
  log:close()
  manager.machine:exit()
end

local function on_frame()
  frame = frame + 1
  if CONFIG.inject_preset == "coin_start" then
    if frame == 1 then
      coin = find_field("Coin 1")
      start = find_field("1 Player Start") or find_field("P1 Start")
      w(string.format("# inject enabled: coin=%s start=%s", tostring(coin ~= nil), tostring(start ~= nil)))
    end
    local act = schedule[frame]
    if act then act() end
  end
  if frame >= CONFIG.frames then dump_and_exit() end
end

w("# mame_mcp memory access trace")
w(string.format("# frames %d", CONFIG.frames))
for _, r in ipairs(CONFIG.ranges) do
  w(string.format("# range %s $%06X-$%06X", r.name, r.start, r.stop))
end

if emu.register_frame_done then emu.register_frame_done(on_frame)
elseif emu.register_frame then emu.register_frame(on_frame)
else error("MAME Lua frame callback API unavailable") end
